apiVersion: v1
kind: ServiceAccount
metadata:
  name: hub
  labels:
    component: jupyter
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hub
  labels:
    component: jupyter
rules:
  - apiGroups: [""]       # "" indicates the core API group
    resources: ["pods", "persistentvolumeclaims"]
    verbs: ["get", "watch", "list", "create", "delete"]
  - apiGroups: [""]       # "" indicates the core API group
    resources: ["events"]
    verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hub
  labels:
    component: jupyter
subjects:
  - kind: ServiceAccount
    name: hub
    namespace:
roleRef:
  kind: Role
  name: hub
  apiGroup: rbac.authorization.k8s.io