apiVersion: v1
kind: Service
metadata:
  name: proxy-api
  labels:
    component: proxy
spec:
  selector:
    component: proxy
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-public
  labels:
    component: proxy
spec:
  selector:
    component: proxy
  ports:
    - name: https
      port: 443
      protocol: TCP
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
      targetPort: 8000
      # allow proxy.service.nodePort for http
      #{{- if .Values.proxy.service.nodePorts.http }}
      #nodePort: {{ .Values.proxy.service.nodePorts.http }}
      #{{- end }}
  type: LoadBalancer
